name: Build

on:
  push:
    branches: [ develop_action ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: x64
      - name: Build with Maven
        run: mvn -B install
